version: '3.9'

services:
  db:
    container_name: users-db
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
